title = 'chems'
languageCode = 'en-us'
enableGitInfo = true
disableKinds = ['taxonomy', 'term', 'tier', 'class', 'nation']

[frontmatter]
  lastmod = ['lastmod', ':git', ':fileModTime', ':default']

[taxonomies]
  tier = 'tier'
  class = 'class'
  nation = 'nation'
